### ISSUE TITLE
how i add custom style

### ISSUE THREAD

**Issue by arydevy** [pokepetter/simple_static_website_generator#2]

**Comment by arydevy** [comment]
also what if i have files is sub dirs like @pokepetter  
```
├── [1.6K]  comunity.html
├── [ 403]  comunity.txt
├── [1.7K]  contrib.html
├── [ 453]  contrib.txt
├── [4.0K]  docs
│   └── [  73]  docs.txt
├── [4.0K]  img
│   ├── [ 16K]  ary.jpg
│   ├── [5.5K]  discord_icon.png
│   ├── [4.3K]  github_icon.png
│   └── [2.2K]  matrix_icon.png
├── [2.6K]  index.html
└── [1.0K]  index.txt```
how i compile the one in docs?

**Comment by pokepetter** [comment]
If you need more than tags for alignment, font and background color you can use whatever html and css you want in a document. There's no way to have a global styling though, at least not yet.

As for subfolders, you can just separately run swwg there. You can do this easily with a script or by running several commands at once.

**Comment by pokepetter** [comment]
Actually, you have to prefix it with # style
Example: `# style a.button {background-color: #6b943a;} a.button:hover {background-color: #a9a33a}`

**Comment by arydevy** [comment]
Thats enorh cuz i make a gameengine documentation i wanted to change some colors
